plugins { id 'net.minecraftforge.gradle' version '7.0.38' }
minecraft {
    runs {
        configureEach {
            workingDir = layout.projectDirectory.dir('run')
            args '--mixin.config=eatinganimation.mixins.json'
            systemProperty 'eventbus.api.strictRuntimeChecks', 'true'
        }
        register('client')
        register('server') { args '--nogui' }
    }
}
repositories {
    minecraft.mavenizer(it)
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven
}
dependencies {
    implementation minecraft.dependency("net.minecraftforge:forge:${minecraft_version}-${forge_version}")
}
jar { manifest.attributes('MixinConfigs': 'eatinganimation.mixins.json') }
